In [1]:
import numpy as np
import pandas as pd

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
# Set Pandas display options to show all rows and columns
pd.set_option('display.max_rows', None)  # None means unlimited
pd.set_option('display.max_columns', None)

In [4]:
data = pd.read_excel('INX_Future_Inc_Employee_Performance_CDS_Project2_Data_V1.8.xls')
data

     EmpNumber  Age  Gender EducationBackground MaritalStatus  \
0     E1001000   32    Male           Marketing        Single
1     E1001006   47    Male           Marketing        Single
2     E1001007   40    Male       Life Sciences       Married
3     E1001009   41    Male     Human Resources      Divorced
4     E1001010   60    Male           Marketing        Single
5     E1001011   27    Male       Life Sciences      Divorced
6     E1001016   50    Male           Marketing       Married
7     E1001019   28  Female       Life Sciences        Single
8     E1001020   36  Female       Life Sciences       Married
9     E1001021   38  Female       Life Sciences        Single
10    E1001022   44    Male             Medical        Single
11    E1001024   47  Female             Medical      Divorced
12    E1001025   30    Male           Marketing      Divorced
13    E1001027   29    Male       Life Sciences        Single
14    E1001030   42    Male             Medical      Divorced
15    E1001035   34  Female             Medical        Single
16    E1001038   39  Female     Human Resources       Married
17    E1001040   56    Male             Medical       Married
18    E1001041   40  Female             Medical        Single
19    E1001042   27  Female             Medical        Single
20    E1001044   29    Male           Marketing      Divorced
21    E1001047   53    Male       Life Sciences        Single
22    E1001049   35  Female       Life Sciences      Divorced
23    E1001050   32    Male       Life Sciences       Married
24    E1001053   34  Female       Life Sciences      Divorced
25    E1001054   52    Male           Marketing       Married
26    E1001058   33    Male               Other        Single
27    E1001059   25  Female             Medical        Single
28    E1001061   45    Male    Technical Degree        Single
29    E1001062   23    Male             Medical        Single
30    E1001063   47  Female       Life Sciences        Single
31    E1001064   34    Male               Other        Single
32    E1001067   36    Male       Life Sciences        Single
33    E1001069   52    Male             Medical       Married
34    E1001070   26  Female       Life Sciences      Divorced
35    E1001071   29  Female             Medical       Married
36    E1001074   26    Male    Technical Degree        Single
37    E1001075   34  Female       Life Sciences        Single
38    E1001077   54  Female             Medical      Divorced
39    E1001078   27    Male           Marketing       Married
40    E1001080   37  Female       Life Sciences      Divorced
41    E1001081   38  Female       Life Sciences        Single
42    E1001082   34  Female             Medical        Single
43    E1001083   35  Female       Life Sciences       Married
44    E1001085   40  Female             Medical       Married
45    E1001086   34  Female       Life Sciences       Married
46    E1001090   24    Male       Life Sciences      Divorced
47    E1001091   52  Female       Life Sciences       Married
48    E1001093   50    Male             Medical       Married
49    E1001094   29  Female       Life Sciences       Married
50    E1001095   33    Male             Medical       Married
51    E1001097   33  Female           Marketing        Single
52    E1001098   47  Female               Other       Married
53    E1001101   36  Female               Other       Married
54    E1001102   29    Male       Life Sciences       Married
55    E1001104   35  Female       Life Sciences        Single
56    E1001105   42  Female       Life Sciences       Married
57    E1001106   28    Male             Medical        Single
58    E1001107   36    Male     Human Resources       Married
59    E1001110   40    Male             Medical        Single
60    E1001111   30  Female             Medical        Single
61    E1001112   45  Female       Life Sciences        Single
62    E1001114   42    Male       Life Sciences       Married
63    E1001115   38    Male       Life Sciences      Divorced
64    E1001118   49  Female           Marketing       Married
65    E1001120   55    Male             Medical        Single
66    E1001121   43    Male       Life Sciences       Married
67    E1001122   27    Male    Technical Degree      Divorced
68    E1001123   35    Male               Other        Single
69    E1001124   28  Female           Marketing       Married
70    E1001126   26  Female             Medical       Married
71    E1001128   27    Male             Medical       Married
72    E1001129   51  Female           Marketing       Married
73    E1001130   44    Male             Medical        Single
74    E1001132   25    Male             Medical        Single
75    E1001134   35  Female             Medical        Single
76    E1001135   36    Male       Life Sciences       Married
77    E1001140   53  Female           Marketing       Married
78    E1001142   45    Male           Marketing      Divorced
79    E1001143   32  Female             Medical       Married
80    E1001146   37    Male           Marketing      Divorced
81    E1001147   28    Male             Medical      Divorced
82    E1001150   22    Male       Life Sciences       Married
83    E1001152   44    Male       Life Sciences       Married
84    E1001153   42    Male             Medical        Single
85    E1001156   36    Male       Life Sciences       Married
86    E1001157   25    Male               Other       Married
87    E1001159   35  Female       Life Sciences      Divorced
88    E1001160   32    Male       Life Sciences      Divorced
89    E1001165   49  Female    Technical Degree       Married
90    E1001166   24    Male       Life Sciences       Married
91    E1001167   32    Male       Life Sciences       Married
92    E1001171   38    Male           Marketing       Married
93    E1001173   31    Male       Life Sciences       Married
94    E1001175   53    Male           Marketing       Married
95    E1001178   37  Female             Medical       Married
96    E1001179   53  Female       Life Sciences        Single
97    E1001180   43  Female       Life Sciences       Married
98    E1001181   47  Female           Marketing       Married
99    E1001182   37    Male             Medical        Single
100   E1001183   50    Male       Life Sciences      Divorced
101   E1001187   39  Female       Life Sciences       Married
102   E1001188   33    Male     Human Resources      Divorced
103   E1001189   32    Male       Life Sciences        Single
104   E1001191   44    Male       Life Sciences       Married
105   E1001196   58    Male       Life Sciences      Divorced
106   E1001200   20  Female             Medical        Single
107   E1001201   21  Female               Other        Single
108   E1001202   36    Male       Life Sciences       Married
109   E1001203   47  Female       Life Sciences        Single
110   E1001204   22  Female       Life Sciences       Married
111   E1001208   28  Female             Medical      Divorced
112   E1001210   39    Male             Medical       Married
113   E1001211   27  Female       Life Sciences        Single
114   E1001212   34    Male       Life Sciences      Divorced
115   E1001214   42  Female             Medical        Single
116   E1001217   33    Male               Other        Single
117   E1001218   58  Female    Technical Degree      Divorced
118   E1001219   31    Male       Life Sciences       Married
119   E1001220   35  Female       Life Sciences       Married
120   E1001223   48    Male             Medical       Married
121   E1001225   31  Female           Marketing       Married
122   E1001227   36    Male               Other        Single
123   E1001228   38  Female    Technical Degree       Married
124   E1001229   32  Female       Life Sciences       Married
125   E1001230   25    Male           Marketing       Married
126   E1001235   41    Male             Medical        Single
127   E1001236   36    Male             Medical        Single
128   E1001237   19    Male               Other        Single
129   E1001238   20    Male    Technical Degree        Single
130   E1001239   31  Female             Medical       Married
131   E1001245   36    Male       Life Sciences       Married
132   E1001248   37    Male       Life Sciences       Married
133   E1001250   45    Male       Life Sciences       Married
134   E1001252   29  Female    Technical Degree       Married
135   E1001253   35  Female             Medical       Married
136   E1001254   52    Male       Life Sciences       Married
137   E1001259   53    Male             Medical      Divorced
138   E1001260   30    Male               Other      Divorced
139   E1001262   35    Male       Life Sciences      Divorced
140   E1001263   39    Male       Life Sciences        Single
141   E1001264   40  Female       Life Sciences        Single
142   E1001265   47    Male             Medical      Divorced
143   E1001268   36    Male    Technical Degree      Divorced
144   E1001269   31    Male             Medical        Single
145   E1001270   33    Male       Life Sciences        Single
146   E1001272   29  Female       Life Sciences        Single
147   E1001273   33  Female       Life Sciences        Single
148   E1001274   45  Female             Medical      Divorced
149   E1001275   50    Male             Medical      Divorced
150   E1001276   33  Female               Other       Married
151   E1001277   41    Male             Medical      Divorced
152   E1001280   45    Male       Life Sciences       Married
153   E1001281   47  Female       Life Sciences        Single
154   E1001282   30  Female       Life Sciences       Married
155   E1001283   50    Male       Life Sciences       Married
156   E1001284   38    Male             Medical       Married
157   E1001288   35    Male               Other      Divorced
158   E1001289   31  Female       Life Sciences       Married
159   E1001290   18    Male       Life Sciences        Single
160   E1001291   54  Female    Technical Degree       Married
161   E1001292   35  Female             Medical      Divorced
162   E1001293   30  Female       Life Sciences       Married
163   E1001296   26    Male             Medical       Married
164   E1001297   22    Male       Life Sciences       Married
165   E1001300   48    Male       Life Sciences        Single
166   E1001302   48    Male       Life Sciences        Single
167   E1001303   41  Female             Medical        Single
168   E1001304   39  Female       Life Sciences       Married
169   E1001305   27  Female       Life Sciences       Married
170   E1001306   35    Male               Other      Divorced
171   E1001307   42    Male           Marketing       Married
172   E1001308   50    Male       Life Sciences       Married
173   E1001310   59  Female       Life Sciences        Single
174   E1001312   55    Male             Medical       Married
175   E1001313   41  Female       Life Sciences      Divorced
176   E1001314   38    Male       Life Sciences        Single
177   E1001315   26    Male             Medical        Single
178   E1001316   52  Female           Marketing       Married
179   E1001317   44  Female             Medical       Married
180   E1001318   50  Female       Life Sciences       Married
181   E1001321   39  Female             Medical        Single
182   E1001322   33  Female       Life Sciences        Single
183   E1001323   45  Female       Life Sciences       Married
184   E1001324   32  Female             Medical        Single
185   E1001325   34    Male           Marketing      Divorced
186   E1001326   59    Male    Technical Degree       Married
187   E1001327   45    Male             Medical        Single
188   E1001330   36    Male               Other      Divorced
189   E1001331   26    Male       Life Sciences       Married
190   E1001334   28    Male             Medical       Married
191   E1001338   38    Male               Other       Married
192   E1001339   50    Male             Medical       Married
193   E1001340   37  Female               Other        Single
194   E1001344   40    Male           Marketing       Married
195   E1001346   26  Female             Medical      Divorced
196   E1001348   54  Female       Life Sciences       Married
197   E1001349   56  Female             Medical       Married
198   E1001351   36  Female             Medical        Single
199   E1001352   55    Male             Medical        Single
200   E1001354   43    Male             Medical      Divorced
201   E1001355   20  Female           Marketing        Single
202   E1001357   21  Female       Life Sciences        Single
203   E1001358   46  Female       Life Sciences      Divorced
204   E1001360   28    Male    Technical Degree        Single
205   E1001361   26    Male             Medical       Married
206   E1001362   30    Male               Other       Married
207   E1001366   38  Female       Life Sciences       Married
208   E1001370   40    Male    Technical Degree       Married
209   E1001372   27    Male       Life Sciences       Married
210   E1001374   55    Male       Life Sciences       Married
211   E1001376   44    Male             Medical       Married
212   E1001379   33  Female             Medical        Single
213   E1001381   34    Male       Life Sciences        Single
214   E1001384   25    Male    Technical Degree       Married
215   E1001385   26    Male             Medical      Divorced
216   E1001387   42    Male             Medical       Married
217   E1001389   28    Male             Medical      Divorced
218   E1001391   50    Male               Other        Single
219   E1001392   33  Female       Life Sciences       Married
220   E1001393   34    Male       Life Sciences       Married
221   E1001394   48    Male             Medical        Single
222   E1001395   45  Female       Life Sciences       Married
223   E1001396   52    Male       Life Sciences        Single
224   E1001397   38    Male           Marketing      Divorced
225   E1001398   29  Female       Life Sciences      Divorced
226   E1001399   28  Female             Medical      Divorced
227   E1001402   46    Male           Marketing       Married
228   E1001403   38    Male           Marketing        Single
229   E1001405   39    Male       Life Sciences      Divorced
230   E1001406   40    Male             Medical        Single
231   E1001410   39    Male       Life Sciences        Single
232   E1001411   36    Male       Life Sciences        Single
233   E1001413   31    Male       Life Sciences       Married
234   E1001414   28    Male       Life Sciences       Married
235   E1001415   35    Male           Marketing      Divorced
236   E1001416   49    Male    Technical Degree       Married
237   E1001418   34    Male       Life Sciences        Single
238   E1001421   29  Female       Life Sciences      Divorced
239   E1001426   42    Male             Medical        Single
240   E1001428   29    Male             Medical       Married
241   E1001432   28    Male       Life Sciences      Divorced
242   E1001434   18    Male             Medical        Single
243   E1001435   33  Female           Marketing        Single
244   E1001436   41    Male       Life Sciences       Married
245   E1001438   31    Male             Medical       Married
246   E1001439   37  Female             Medical      Divorced
247   E1001440   27    Male       Life Sciences       Married
248   E1001441   34  Female       Life Sciences       Married
249   E1001442   35    Male    Technical Degree        Single
250   E1001443   29  Female       Life Sciences       Married
251   E1001444   40  Female             Medical        Single
252   E1001445   42    Male       Life Sciences        Single
253   E1001449   42    Male           Marketing        Single
254   E1001451   24    Male             Medical        Single
255   E1001453   28  Female       Life Sciences       Married
256   E1001455   26    Male             Medical       Married
257   E1001457   30    Male           Marketing       Married
258   E1001458   40  Female             Medical       Married
259   E1001460   35    Male       Life Sciences      Divorced
260   E1001462   34    Male             Medical        Single
261   E1001463   35    Male               Other       Married
262   E1001466   43  Female           Marketing        Single
263   E1001468   32  Female       Life Sciences      Divorced
264   E1001469   56  Female    Technical Degree      Divorced
265   E1001470   29  Female             Medical       Married
266   E1001471   19    Male       Life Sciences        Single
267   E1001473   45  Female             Medical       Married
268   E1001474   37  Female       Life Sciences       Married
269   E1001478   44    Male       Life Sciences        Single
270   E1001479   53  Female             Medical      Divorced
271   E1001481   22    Male       Life Sciences       Married
272   E1001482   46  Female           Marketing       Married
273   E1001484   44    Male       Life Sciences        Single
274   E1001485   33    Male     Human Resources       Married
275   E1001489   30    Male       Life Sciences      Divorced
276   E1001490   40    Male             Medical       Married
277   E1001493   50  Female             Medical       Married
278   E1001495   46    Male       Life Sciences       Married
279   E1001496   35    Male       Life Sciences       Married
280   E1001497   24  Female       Life Sciences       Married
281   E1001498   33  Female             Medical       Married
282   E1001499   36    Male       Life Sciences      Divorced
283   E1001503   44    Male               Other        Single
284   E1001509   42    Male             Medical       Married
285   E1001512   32  Female               Other       Married
286   E1001513   32  Female       Life Sciences        Single
287   E1001515   36  Female    Technical Degree      Divorced
288   E1001516   33    Male             Medical       Married
289   E1001518   25    Male       Life Sciences        Single
290   E1001520   42  Female             Medical       Married
291   E1001522   27    Male       Life Sciences       Married
292   E1001523   54  Female       Life Sciences      Divorced
293   E1001524   44  Female       Life Sciences       Married
294   E1001526   19  Female             Medical        Single
295   E1001528   54    Male       Life Sciences       Married
296   E1001529   31    Male             Medical       Married
297   E1001533   43    Male       Life Sciences       Married
298   E1001534   49    Male             Medical       Married
299   E1001535   36    Male    Technical Degree       Married
300   E1001536   48    Male    Technical Degree        Single
301   E1001538   29    Male       Life Sciences      Divorced
302   E1001541   48    Male       Life Sciences        Single
303   E1001542   29  Female       Life Sciences      Divorced
304   E1001545   44    Male           Marketing       Married
305   E1001548   23    Male       Life Sciences       Married
306   E1001553   26    Male       Life Sciences        Single
307   E1001555   45  Female           Marketing        Single
308   E1001556   55    Male             Medical      Divorced
309   E1001557   21  Female       Life Sciences        Single
310   E1001558   46  Female           Marketing       Married
311   E1001559   34  Female           Marketing        Single
312   E1001560   51    Male       Life Sciences      Divorced
313   E1001561   59    Male             Medical        Single
314   E1001563   34  Female             Medical      Divorced
315   E1001564   28    Male             Medical        Single
316   E1001566   44    Male       Life Sciences      Divorced
317   E1001567   34    Male       Life Sciences       Married
318   E1001569   35    Male       Life Sciences       Married
319   E1001570   42  Female             Medical       Married
320   E1001571   43  Female           Marketing        Single

# Data Preprocessing

### Check percentage of missing values

In [5]:
data.isnull().sum()/len(data)*100

EmpNumber                       0.0
Age                             0.0
Gender                          0.0
EducationBackground             0.0
MaritalStatus                   0.0
EmpDepartment                   0.0
EmpJobRole                      0.0
BusinessTravelFrequency         0.0
DistanceFromHome                0.0
EmpEducationLevel               0.0
EmpEnvironmentSatisfaction      0.0
EmpHourlyRate                   0.0
EmpJobInvolvement               0.0
EmpJobLevel                     0.0
EmpJobSatisfaction              0.0
NumCompaniesWorked              0.0
OverTime                        0.0
EmpLastSalaryHikePercent        0.0
EmpRelationshipSatisfaction     0.0
TotalWorkExperienceInYears      0.0
TrainingTimesLastYear           0.0
EmpWorkLifeBalance              0.0
ExperienceYearsAtThisCompany    0.0
ExperienceYearsInCurrentRole    0.0
YearsSinceLastPromotion         0.0
YearsWithCurrManager            0.0
Attrition                       0.0
PerformanceRating               0.0
dtype: float64

#### Insights:
- We do not have any null values.
- We have two constant features namely Attrition and Performance Rating

In [6]:
data.isnull().sum()

EmpNumber                       0
Age                             0
Gender                          0
EducationBackground             0
MaritalStatus                   0
EmpDepartment                   0
EmpJobRole                      0
BusinessTravelFrequency         0
DistanceFromHome                0
EmpEducationLevel               0
EmpEnvironmentSatisfaction      0
EmpHourlyRate                   0
EmpJobInvolvement               0
EmpJobLevel                     0
EmpJobSatisfaction              0
NumCompaniesWorked              0
OverTime                        0
EmpLastSalaryHikePercent        0
EmpRelationshipSatisfaction     0
TotalWorkExperienceInYears      0
TrainingTimesLastYear           0
EmpWorkLifeBalance              0
ExperienceYearsAtThisCompany    0
ExperienceYearsInCurrentRole    0
YearsSinceLastPromotion         0
YearsWithCurrManager            0
Attrition                       0
PerformanceRating               0
dtype: int64

### In Attrition and Gender, there are only two categorical variables, so we can encode them as 0 or 1

In [7]:
data['Attrition'] = data.Attrition.replace({'Yes':1,'No':0})

In [8]:
data['OverTime'] = data.OverTime.replace({'Yes':1,'No':0})

In [9]:
data['Gender'] = data.Gender.replace({'Male':1,'Female':0})

## We are using LabelEncoder because there are too many values in the categorical columns

In [10]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
BusinessTravelFrequency = encoder.fit_transform(data.BusinessTravelFrequency)
data['BusinessTravelFrequency']=pd.DataFrame(BusinessTravelFrequency)

In [11]:
EmpDepartment = encoder.fit_transform(data.EmpDepartment)
data['EmpDepartment']=pd.DataFrame(EmpDepartment)

In [12]:
EmpJobRole = encoder.fit_transform(data.EmpJobRole)
data['EmpJobRole']=pd.DataFrame(EmpJobRole)

In [13]:
MaritalStatus = encoder.fit_transform(data.MaritalStatus)
data['MaritalStatus']=pd.DataFrame(MaritalStatus)

In [14]:
EmpNumber = encoder.fit_transform(data.EmpNumber)
data['EmpNumber']=pd.DataFrame(EmpNumber)

In [15]:
EducationBackground = encoder.fit_transform(data.EducationBackground)
data['EducationBackground']=pd.DataFrame(EducationBackground)

#### Checking Mean, Median and Mode.

In [16]:
print(data.mean())

EmpNumber                       599.500000
Age                              36.918333
Gender                            0.604167
EducationBackground               2.235000
MaritalStatus                     1.096667
EmpDepartment                     3.215000
EmpJobRole                        9.039167
BusinessTravelFrequency           1.595000
DistanceFromHome                  9.165833
EmpEducationLevel                 2.892500
EmpEnvironmentSatisfaction        2.715833
EmpHourlyRate                    65.981667
EmpJobInvolvement                 2.731667
EmpJobLevel                       2.067500
EmpJobSatisfaction                2.732500
NumCompaniesWorked                2.665000
OverTime                          0.294167
EmpLastSalaryHikePercent         15.222500
EmpRelationshipSatisfaction       2.725000
TotalWorkExperienceInYears       11.330000
TrainingTimesLastYear             2.785833
EmpWorkLifeBalance                2.744167
ExperienceYearsAtThisCompany      7.077500
ExperienceYearsInCurrentRole      4.291667
YearsSinceLastPromotion           2.194167
YearsWithCurrManager              4.105000
Attrition                         0.148333
PerformanceRating                 2.948333
dtype: float64

In [17]:
print(data.median())

EmpNumber                       599.5
Age                              36.0
Gender                            1.0
EducationBackground               2.0
MaritalStatus                     1.0
EmpDepartment                     4.0
EmpJobRole                        9.0
BusinessTravelFrequency           2.0
DistanceFromHome                  7.0
EmpEducationLevel                 3.0
EmpEnvironmentSatisfaction        3.0
EmpHourlyRate                    66.0
EmpJobInvolvement                 3.0
EmpJobLevel                       2.0
EmpJobSatisfaction                3.0
NumCompaniesWorked                2.0
OverTime                          0.0
EmpLastSalaryHikePercent         14.0
EmpRelationshipSatisfaction       3.0
TotalWorkExperienceInYears       10.0
TrainingTimesLastYear             3.0
EmpWorkLifeBalance                3.0
ExperienceYearsAtThisCompany      5.0
ExperienceYearsInCurrentRole      3.0
YearsSinceLastPromotion           1.0
YearsWithCurrManager              3.0
Attrition                         0.0
PerformanceRating                 3.0
dtype: float64

In [18]:
print(data.mode())

      EmpNumber   Age  Gender  EducationBackground  MaritalStatus  \
0             0  34.0     1.0                  1.0            1.0
1             1   NaN     NaN                  NaN            NaN
2             2   NaN     NaN                  NaN            NaN
3             3   NaN     NaN                  NaN            NaN
4             4   NaN     NaN                  NaN            NaN
5             5   NaN     NaN                  NaN            NaN
6             6   NaN     NaN                  NaN            NaN
7             7   NaN     NaN                  NaN            NaN
8             8   NaN     NaN                  NaN            NaN
9             9   NaN     NaN                  NaN            NaN
10           10   NaN     NaN                  NaN            NaN
11           11   NaN     NaN                  NaN            NaN
12           12   NaN     NaN                  NaN            NaN
13           13   NaN     NaN                  NaN            NaN
14           14   NaN     NaN                  NaN            NaN
15           15   NaN     NaN                  NaN            NaN
16           16   NaN     NaN                  NaN            NaN
17           17   NaN     NaN                  NaN            NaN
18           18   NaN     NaN                  NaN            NaN
19           19   NaN     NaN                  NaN            NaN
20           20   NaN     NaN                  NaN            NaN
21           21   NaN     NaN                  NaN            NaN
22           22   NaN     NaN                  NaN            NaN
23           23   NaN     NaN                  NaN            NaN
24           24   NaN     NaN                  NaN            NaN
25           25   NaN     NaN                  NaN            NaN
26           26   NaN     NaN                  NaN            NaN
27           27   NaN     NaN                  NaN            NaN
28           28   NaN     NaN                  NaN            NaN
29           29   NaN     NaN                  NaN            NaN
30           30   NaN     NaN                  NaN            NaN
31           31   NaN     NaN                  NaN            NaN
32           32   NaN     NaN                  NaN            NaN
33           33   NaN     NaN                  NaN            NaN
34           34   NaN     NaN                  NaN            NaN
35           35   NaN     NaN                  NaN            NaN
36           36   NaN     NaN                  NaN            NaN
37           37   NaN     NaN                  NaN            NaN
38           38   NaN     NaN                  NaN            NaN
39           39   NaN     NaN                  NaN            NaN
40           40   NaN     NaN                  NaN            NaN
41           41   NaN     NaN                  NaN            NaN
42           42   NaN     NaN                  NaN            NaN
43           43   NaN     NaN                  NaN            NaN
44           44   NaN     NaN                  NaN            NaN
45           45   NaN     NaN                  NaN            NaN
46           46   NaN     NaN                  NaN            NaN
47           47   NaN     NaN                  NaN            NaN
48           48   NaN     NaN                  NaN            NaN
49           49   NaN     NaN                  NaN            NaN
50           50   NaN     NaN                  NaN            NaN
51           51   NaN     NaN                  NaN            NaN
52           52   NaN     NaN                  NaN            NaN
53           53   NaN     NaN                  NaN            NaN
54           54   NaN     NaN                  NaN            NaN
55           55   NaN     NaN                  NaN            NaN
56           56   NaN     NaN                  NaN            NaN
57           57   NaN     NaN                  NaN            NaN
58           58   NaN     NaN                  NaN            NaN
59           59   NaN     NaN                  NaN            NaN
60           60   NaN     NaN                  NaN            NaN
61           61   NaN     NaN                  NaN            NaN
62           62   NaN     NaN                  NaN            NaN
63           63   NaN     NaN                  NaN            NaN
64           64   NaN     NaN                  NaN            NaN
65           65   NaN     NaN                  NaN            NaN
66           66   NaN     NaN                  NaN            NaN
67           67   NaN     NaN                  NaN            NaN
68           68   NaN     NaN                  NaN            NaN
69           69   NaN     NaN                  NaN            NaN
70           70   NaN     NaN                  NaN            NaN
71           71   NaN     NaN                  NaN            NaN
72           72   NaN     NaN                  NaN            NaN
73           73   NaN     NaN                  NaN            NaN
74           74   NaN     NaN                  NaN            NaN
75           75   NaN     NaN                  NaN            NaN
76           76   NaN     NaN                  NaN            NaN
77           77   NaN     NaN                  NaN            NaN
78           78   NaN     NaN                  NaN            NaN
79           79   NaN     NaN                  NaN            NaN
80           80   NaN     NaN                  NaN            NaN
81           81   NaN     NaN                  NaN            NaN
82           82   NaN     NaN                  NaN            NaN
83           83   NaN     NaN                  NaN            NaN
84           84   NaN     NaN                  NaN            NaN
85           85   NaN     NaN                  NaN            NaN
86           86   NaN     NaN                  NaN            NaN
87           87   NaN     NaN                  NaN            NaN
88           88   NaN     NaN                  NaN            NaN
89           89   NaN     NaN                  NaN            NaN
90           90   NaN     NaN                  NaN            NaN
91           91   NaN     NaN                  NaN            NaN
92           92   NaN     NaN                  NaN            NaN
93           93   NaN     NaN                  NaN            NaN
94           94   NaN     NaN                  NaN            NaN
95           95   NaN     NaN                  NaN            NaN
96           96   NaN     NaN                  NaN            NaN
97           97   NaN     NaN                  NaN            NaN
98           98   NaN     NaN                  NaN            NaN
99           99   NaN     NaN                  NaN            NaN
100         100   NaN     NaN                  NaN            NaN
101         101   NaN     NaN                  NaN            NaN
102         102   NaN     NaN                  NaN            NaN
103         103   NaN     NaN                  NaN            NaN
104         104   NaN     NaN                  NaN            NaN
105         105   NaN     NaN                  NaN            NaN
106         106   NaN     NaN                  NaN            NaN
107         107   NaN     NaN                  NaN            NaN
108         108   NaN     NaN                  NaN            NaN
109         109   NaN     NaN                  NaN            NaN
110         110   NaN     NaN                  NaN            NaN
111         111   NaN     NaN                  NaN            NaN
112         112   NaN     NaN                  NaN            NaN
113         113   NaN     NaN                  NaN            NaN
114         114   NaN     NaN                  NaN            NaN
115         115   NaN     NaN                  NaN            NaN
116         116   NaN     NaN                  NaN            NaN
117         117   NaN     NaN                  NaN            NaN
118         118   NaN     NaN                  NaN            NaN
119         119   NaN     NaN                  NaN            NaN
120         120   NaN     NaN                  NaN            NaN
121         121   NaN     NaN                  NaN            NaN
122         122   NaN     NaN                  NaN            NaN
123         123   NaN     NaN                  NaN            NaN
124         124   NaN     NaN                  NaN            NaN
125         125   NaN     NaN                  NaN            NaN
126         126   NaN     NaN                  NaN            NaN
127         127   NaN     NaN                  NaN            NaN
128         128   NaN     NaN                  NaN            NaN
129         129   NaN     NaN                  NaN            NaN
130         130   NaN     NaN                  NaN            NaN
131         131   NaN     NaN                  NaN            NaN
132         132   NaN     NaN                  NaN            NaN
133         133   NaN     NaN                  NaN            NaN
134         134   NaN     NaN                  NaN            NaN
135         135   NaN     NaN                  NaN            NaN
136         136   NaN     NaN                  NaN            NaN
137         137   NaN     NaN                  NaN            NaN
138         138   NaN     NaN                  NaN            NaN
139         139   NaN     NaN                  NaN            NaN
140         140   NaN     NaN                  NaN            NaN
141         141   NaN     NaN                  NaN            NaN
142         142   NaN     NaN                  NaN            NaN
143         143   NaN     NaN                  NaN            NaN
144         144   NaN     NaN                  NaN            NaN
145         145   NaN     NaN                  NaN            NaN
146         146   NaN     NaN                  NaN            NaN
147         147   NaN     NaN                  NaN            NaN
148         148   NaN     NaN                  NaN            NaN
149         149   NaN     NaN                  NaN            NaN
150         150   NaN     NaN                  NaN            NaN
151         151   NaN     NaN                  NaN            NaN
152         152   NaN     NaN                  NaN            NaN
153         153   NaN     NaN                  NaN            NaN
154         154   NaN     NaN                  NaN            NaN
155         155   NaN     NaN                  NaN            NaN
156         156   NaN     NaN                  NaN            NaN
157         157   NaN     NaN                  NaN            NaN
158         158   NaN     NaN                  NaN            NaN
159         159   NaN     NaN                  NaN            NaN
160         160   NaN     NaN                  NaN            NaN
161         161   NaN     NaN                  NaN            NaN
162         162   NaN     NaN                  NaN            NaN
163         163   NaN     NaN                  NaN            NaN
164         164   NaN     NaN                  NaN            NaN
165         165   NaN     NaN                  NaN            NaN
166         166   NaN     NaN                  NaN            NaN
167         167   NaN     NaN                  NaN            NaN
168         168   NaN     NaN                  NaN            NaN
169         169   NaN     NaN                  NaN            NaN
170         170   NaN     NaN                  NaN            NaN
171         171   NaN     NaN                  NaN            NaN
172         172   NaN     NaN                  NaN            NaN
173         173   NaN     NaN                  NaN            NaN
174         174   NaN     NaN                  NaN            NaN
175         175   NaN     NaN                  NaN            NaN
176         176   NaN     NaN                  NaN            NaN
177         177   NaN     NaN                  NaN            NaN
178         178   NaN     NaN                  NaN            NaN
179         179   NaN     NaN                  NaN            NaN
180         180   NaN     NaN                  NaN            NaN
181         181   NaN     NaN                  NaN            NaN
182         182   NaN     NaN                  NaN            NaN
183         183   NaN     NaN                  NaN            NaN
184         184   NaN     NaN                  NaN            NaN
185         185   NaN     NaN                  NaN            NaN
186         186   NaN     NaN                  NaN            NaN
187         187   NaN     NaN                  NaN            NaN
188         188   NaN     NaN                  NaN            NaN
189         189   NaN     NaN                  NaN            NaN
190         190   NaN     NaN                  NaN            NaN
191         191   NaN     NaN                  NaN            NaN
192         192   NaN     NaN                  NaN            NaN
193         193   NaN     NaN                  NaN            NaN
194         194   NaN     NaN                  NaN            NaN
195         195   NaN     NaN                  NaN            NaN
196         196   NaN     NaN                  NaN            NaN
197         197   NaN     NaN                  NaN            NaN
198         198   NaN     NaN                  NaN            NaN
199         199   NaN     NaN                  NaN            NaN
200         200   NaN     NaN                  NaN            NaN
201         201   NaN     NaN                  NaN            NaN
202         202   NaN     NaN                  NaN            NaN
203         203   NaN     NaN                  NaN            NaN
204         204   NaN     NaN                  NaN            NaN
205         205   NaN     NaN                  NaN            NaN
206         206   NaN     NaN                  NaN            NaN
207         207   NaN     NaN                  NaN            NaN
208         208   NaN     NaN                  NaN            NaN
209         209   NaN     NaN                  NaN            NaN
210         210   NaN     NaN                  NaN            NaN
211         211   NaN     NaN                  NaN            NaN
212         212   NaN     NaN                  NaN            NaN
213         213   NaN     NaN                  NaN            NaN
214         214   NaN     NaN                  NaN            NaN
215         215   NaN     NaN                  NaN            NaN
216         216   NaN     NaN                  NaN            NaN
217         217   NaN     NaN                  NaN            NaN
218         218   NaN     NaN                  NaN            NaN
219         219   NaN     NaN                  NaN            NaN
220         220   NaN     NaN                  NaN            NaN
221         221   NaN     NaN                  NaN            NaN
222         222   NaN     NaN                  NaN            NaN
223         223   NaN     NaN                  NaN            NaN
224         224   NaN     NaN                  NaN            NaN
225         225   NaN     NaN                  NaN            NaN
226         226   NaN     NaN                  NaN            NaN
227         227   NaN     NaN                  NaN            NaN
228         228   NaN     NaN                  NaN            NaN
229         229   NaN     NaN                  NaN            NaN
230         230   NaN     NaN                  NaN            NaN
231         231   NaN     NaN                  NaN            NaN
232         232   NaN     NaN                  NaN            NaN
233         233   NaN     NaN                  NaN            NaN
234         234   NaN     NaN                  NaN            NaN
235         235   NaN     NaN                  NaN            NaN
236         236   NaN     NaN                  NaN            NaN
237         237   NaN     NaN                  NaN            NaN
238         238   NaN     NaN                  NaN            NaN
239         239   NaN     NaN                  NaN            NaN
240         240   NaN     NaN                  NaN            NaN
241         241   NaN     NaN                  NaN            NaN
242         242   NaN     NaN                  NaN            NaN
243         243   NaN     NaN                  NaN            NaN
244         244   NaN     NaN                  NaN            NaN
245         245   NaN     NaN                  NaN            NaN
246         246   NaN     NaN                  NaN            NaN
247         247   NaN     NaN                  NaN            NaN
248         248   NaN     NaN                  NaN            NaN
249         249   NaN     NaN                  NaN            NaN
250         250   NaN     NaN                  NaN            NaN
251         251   NaN     NaN                  NaN            NaN
252         252   NaN     NaN                  NaN            NaN
253         253   NaN     NaN                  NaN            NaN
254         254   NaN     NaN                  NaN            NaN
255         255   NaN     NaN                  NaN            NaN
256         256   NaN     NaN                  NaN            NaN
257         257   NaN     NaN                  NaN            NaN
258         258   NaN     NaN                  NaN            NaN
259         259   NaN     NaN                  NaN            NaN
260         260   NaN     NaN                  NaN            NaN
261         261   NaN     NaN                  NaN            NaN
262         262   NaN     NaN                  NaN            NaN
263         263   NaN     NaN                  NaN            NaN
264         264   NaN     NaN                  NaN            NaN
265         265   NaN     NaN                  NaN            NaN
266         266   NaN     NaN                  NaN            NaN
267         267   NaN     NaN                  NaN            NaN
268         268   NaN     NaN                  NaN            NaN
269         269   NaN     NaN                  NaN            NaN
270         270   NaN     NaN                  NaN            NaN
271         271   NaN     NaN                  NaN            NaN
272         272   NaN     NaN                  NaN            NaN
273         273   NaN     NaN                  NaN            NaN
274         274   NaN     NaN                  NaN            NaN
275         275   NaN     NaN                  NaN            NaN
276         276   NaN     NaN                  NaN            NaN
277         277   NaN     NaN                  NaN            NaN
278         278   NaN     NaN                  NaN            NaN
279         279   NaN     NaN                  NaN            NaN
280         280   NaN     NaN                  NaN            NaN
281         281   NaN     NaN                  NaN            NaN
282         282   NaN     NaN                  NaN            NaN
283         283   NaN     NaN                  NaN            NaN
284         284   NaN     NaN                  NaN            NaN
285         285   NaN     NaN                  NaN            NaN
286         286   NaN     NaN                  NaN            NaN
287         287   NaN     NaN                  NaN            NaN
288         288   NaN     NaN                  NaN            NaN
289         289   NaN     NaN                  NaN            NaN
290         290   NaN     NaN                  NaN            NaN
291         291   NaN     NaN                  NaN            NaN
292         292   NaN     NaN                  NaN            NaN
293         293   NaN     NaN                  NaN            NaN
294         294   NaN     NaN                  NaN            NaN
295         295   NaN     NaN                  NaN            NaN
296         296   NaN     NaN                  NaN            NaN
297         297   NaN     NaN                  NaN            NaN
298         298   NaN     NaN                  NaN            NaN
299         299   NaN     NaN                  NaN            NaN
300         300   NaN     NaN                  NaN            NaN

In [19]:
data.PerformanceRating.value_counts()

PerformanceRating
3    874
2    194
4    132
Name: count, dtype: int64

### Employee Number doesn't give any information about the performance. So we can remove it

In [20]:
data.drop(columns=['EmpNumber'], inplace=True)

In [21]:
print(data.columns)

Index(['Age', 'Gender', 'EducationBackground', 'MaritalStatus',
       'EmpDepartment', 'EmpJobRole', 'BusinessTravelFrequency',
       'DistanceFromHome', 'EmpEducationLevel', 'EmpEnvironmentSatisfaction',
       'EmpHourlyRate', 'EmpJobInvolvement', 'EmpJobLevel',
       'EmpJobSatisfaction', 'NumCompaniesWorked', 'OverTime',
       'EmpLastSalaryHikePercent', 'EmpRelationshipSatisfaction',
       'TotalWorkExperienceInYears', 'TrainingTimesLastYear',
       'EmpWorkLifeBalance', 'ExperienceYearsAtThisCompany',
       'ExperienceYearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager', 'Attrition', 'PerformanceRating'],
      dtype='object')

# Feature Selection

In [22]:
# checking which columns have standard deviation 0 and remove that
stdev=[]
for column in data.columns:
    if data[column].dtype == 'int64':
        if np.std(data[column])==0:
            stdev.append(column)

In [23]:
stdev

[]

### There is no columns which have Standard Deviation zero. So there is nothing to remove.

## Save the encoded file as CSV

In [24]:
data.to_csv('Encoded.csv', index=False)